---
title: "CodeBook"
author: "LucyKS"
date: "18/12/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Peer-graded Assignment: Getting and Cleaning Data Course Project CodeBook

---

### Data source

The features for this project come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals. Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm. 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals. 

These signals were used to estimate variables of the feature vector for each pattern:  '-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

---

### Tidy_data.txt

tidy_data.txt includes 88 variables (only features that included mean and standard deviation from the original data source) presenting mean values per each of 30 subjects and each of 6 types of activities (this totaling to 180 rows). 

---

#### Subjects and Activities

Two first two variables in the tidy_data are:

* subjectId: subject idenfyfier from 1 to 30
* activityType: activity type performed by a subject.     * Types of activities: walking, walking_upstairs, walking_downstairs, sitting, standing, laying (list of 6)

---

#### Measured Variables Units

* The original acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'.
* The original body acceleration signal obtained by subtracting the gravity from the total acceleration. 
* The origial angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 
* Features are normalized and bounded within [-1,1].

---

#### Mean values of features calculated for each subject and activity are included from 3 to 88 column


  timeDomainBodyAccelerationMeanX
  
  timeDomainBodyAccelerationMeanY
  
  timeDomainBodyAccelerationMeanZ
  
  timeDomainBodyAccelerationStandardDeviationX
  
  timeDomainBodyAccelerationStandardDeviationY
  
  timeDomainBodyAccelerationStandardDeviationZ
  
  timeDomainGravityAccelerationMeanX
  
  timeDomainGravityAccelerationMeanY
  
  timeDomainGravityAccelerationMeanZ
  
  timeDomainGravityAccelerationStandardDeviationX
  
  timeDomainGravityAccelerationStandardDeviationY
  
  timeDomainGravityAccelerationStandardDeviationZ
  
  timeDomainBodyAccelerationJerkMeanX
  
  timeDomainBodyAccelerationJerkMeanY
  
  timeDomainBodyAccelerationJerkMeanZ
  
  timeDomainBodyAccelerationJerkStandardDeviationX
  
  timeDomainBodyAccelerationJerkStandardDeviationY
  
  timeDomainBodyAccelerationJerkStandardDeviationZ
  
  timeDomainBodyGyroscopeMeanX
  
  timeDomainBodyGyroscopeMeanY
  
  timeDomainBodyGyroscopeMeanZ
  
  timeDomainBodyGyroscopeStandardDeviationX
  
  timeDomainBodyGyroscopeStandardDeviationY
  
  timeDomainBodyGyroscopeStandardDeviationZ
  
  timeDomainBodyGyroscopeJerkMeanX
  
  timeDomainBodyGyroscopeJerkMeanY
  
  timeDomainBodyGyroscopeJerkMeanZ
  
  timeDomainBodyGyroscopeJerkStandardDeviationX
  
  timeDomainBodyGyroscopeJerkStandardDeviationY
  
  timeDomainBodyGyroscopeJerkStandardDeviationZ
  
  timeDomainBodyAccelerationMagnitudeMean
  
  timeDomainBodyAccelerationMagnitudeStandardDeviation
  
  timeDomainGravityAccelerationMagnitudeMean
  
  timeDomainGravityAccelerationMagnitudeStandardDeviation
  
  timeDomainBodyAccelerationJerkMagnitudeMean
  
  timeDomainBodyAccelerationJerkMagnitudeStandardDeviation
  
  timeDomainBodyGyroscopeMagnitudeMean
  
  timeDomainBodyGyroscopeMagnitudeStandardDeviation
  
  timeDomainBodyGyroscopeJerkMagnitudeMean
  
  timeDomainBodyGyroscopeJerkMagnitudeStandardDeviation
  
  frequencyDomainBodyAccelerationMeanX
  
  frequencyDomainBodyAccelerationMeanY
  
  frequencyDomainBodyAccelerationMeanZ
  
  frequencyDomainBodyAccelerationStandardDeviationX
  
  frequencyDomainBodyAccelerationStandardDeviationY
  
  frequencyDomainBodyAccelerationStandardDeviationZ
  
  frequencyDomainBodyAccelerationMeanFrequencyX
  
  frequencyDomainBodyAccelerationMeanFrequencyY
  
  frequencyDomainBodyAccelerationMeanFrequencyZ
  
  frequencyDomainBodyAccelerationJerkMeanX
  
  frequencyDomainBodyAccelerationJerkMeanY
  
  frequencyDomainBodyAccelerationJerkMeanZ
  
  frequencyDomainBodyAccelerationJerkStandardDeviationX
  
  frequencyDomainBodyAccelerationJerkStandardDeviationY
  
  frequencyDomainBodyAccelerationJerkStandardDeviationZ
  
  frequencyDomainBodyAccelerationJerkMeanFrequencyX
  
  frequencyDomainBodyAccelerationJerkMeanFrequencyY
  
  frequencyDomainBodyAccelerationJerkMeanFrequencyZ
  
  frequencyDomainBodyGyroscopeMeanX
  
  frequencyDomainBodyGyroscopeMeanY
  
  frequencyDomainBodyGyroscopeMeanZ
  
  frequencyDomainBodyGyroscopeStandardDeviationX
  
  frequencyDomainBodyGyroscopeStandardDeviationY
  
  frequencyDomainBodyGyroscopeStandardDeviationZ
  
  frequencyDomainBodyGyroscopeMeanFrequencyX
  
  frequencyDomainBodyGyroscopeMeanFrequencyY
  
  frequencyDomainBodyGyroscopeMeanFrequencyZ
  
  frequencyDomainBodyAccelerationMagnitudeMean
  
  frequencyDomainBodyAccelerationMagnitudeStandardDeviation
  
  frequencyDomainBodyAccelerationMagnitudeMeanFrequency
  
  frequencyDomainBodyAccelerationJerkMagnitudeMean
  
  frequencyDomainBodyAccelerationJerkMagnitudeStandardDeviation
  
  frequencyDomainBodyAccelerationJerkMagnitudeMeanFrequency
  
  frequencyDomainBodyGyroscopeMagnitudeMean
  
  frequencyDomainBodyGyroscopeMagnitudeStandardDeviation
  
  frequencyDomainBodyGyroscopeMagnitudeMeanFrequency
  
  frequencyDomainBodyGyroscopeJerkMagnitudeMean
  
  frequencyDomainBodyGyroscopeJerkMagnitudeStandardDeviation
  
  frequencyDomainBodyGyroscopeJerkMagnitudeMeanFrequency
  
  angletBodyAccelerationMeanGravity
  
  angletBodyAccelerationJerkMeanGravityMean
  
  angletBodyGyroscopeMeanGravityMean
  
  angletBodyGyroscopeJerkMeanGravityMean
  
  angleXGravityMean
  
  angleYGravityMean
  
  angleZGravityMean
  
